### ISSUE TITLE
generated snippets seems to be old, not in line with the provider's current documentation

### ISSUE THREAD

**Issue by kral2** [run-at-scale/vscode-terraform-doc-snippets#21]
# I have issues

Some generated snippets seems to be old, not in line with the provider's current documentation.

## I'm submitting a

* [x] bug report
* [ ] feature request
* [ ] support request

## What is the current behavior

writing `tf-oci-resource-core_vcn` generates the code block below (pre-HCL2 syntax):
```HCL
resource "oci_core_vcn" "test_vcn" {
    #Required
    cidr_block = "${var.vcn_cidr_block}"
    compartment_id = "${var.compartment_id}"

    #Optional
    defined_tags = {"Operations.CostCenter"= "42"}
    display_name = "${var.vcn_display_name}"
    dns_label = "${var.vcn_dns_label}"
    freeform_tags = {"Department"= "Finance"}
}
```

Whereas the current documentation have the following code block in the documentation: https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_vcn

```HCL
resource "oci_core_vcn" "test_vcn" {
    #Required
    compartment_id = var.compartment_id

    #Optional
    cidr_block = var.vcn_cidr_block
    cidr_blocks = var.vcn_cidr_blocks
    defined_tags = {"Operations.CostCenter"= "42"}
    display_name = var.vcn_display_name
    dns_label = var.vcn_dns_label
    freeform_tags = {"Department"= "Finance"}
    ipv6cidr_block = var.vcn_ipv6cidr_block
    is_ipv6enabled = var.vcn_is_ipv6enabled
}
```

## If this is a bug, how to reproduce? Please include a code sample

In VSCode with the Terraform-doc-snippets extension enabled, type `tf-oci-resource-core_vcn` in a file with a .tf extension and compare the output to the current documentation.
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/core_vcn

## What's the expected behavior

```HCL
resource "oci_core_vcn" "test_vcn" {
    #Required
    compartment_id = var.compartment_id

    #Optional
    cidr_block = var.vcn_cidr_block
    cidr_blocks = var.vcn_cidr_blocks
    defined_tags = {"Operations.CostCenter"= "42"}
    display_name = var.vcn_display_name
    dns_label = var.vcn_dns_label
    freeform_tags = {"Department"= "Finance"}
    ipv6cidr_block = var.vcn_ipv6cidr_block
    is_ipv6enabled = var.vcn_is_ipv6enabled
}
```

## Environment

* Affected module version: 0.4.0
* OS: N/A
* Terraform version: N/A

**Comment by brandonjbjelland** [comment]
Updated them this week in response to your email. Sorry for the delay - working to make the code a little easier to operate regularly.
