### ISSUE TITLE
Auto-completion search aborts when hitting `backspace`

### ISSUE THREAD

**Issue by io41** [run-at-scale/vscode-terraform-doc-snippets#4]
# I have issues

While trying to auto-complete a snippet, when I make a typo and press `backspace` to correct the mistake, VS Code stops attempting to auto-complete the snippet and I have to start typing everything from scratch.

## I'm submitting a

* [x] bug report

## What is the current behavior

When attempting to match (auto-completing) a snippet, pressing the `backspace` key cancels all auto-completion attempts.

## If this is a bug, how to reproduce? Please include a code sample

1. Type `tf-aws-data` but realise you wanted `tf-aws-resource` instead.
2. Hit the `backspace` key multiple times to delete `data`
3. Observe the auto-completion menu disappearing.
4. Attempt to type `resource`. Note how the auto-completion menu stays gone.

## What's the expected behavior

1. Type `tf-aws-data` but realise you wanted `tf-aws-resource` instead.
2. Hit the `backspace` key multiple times to delete `data`
3. The auto-completion menu stays visible, displaying the search results for the corrected input.
4. Attempt to type `resource`. Note how the auto-completion continues to refine the search results with the new input.

## Environment

* Affected module version: 0.3.0
* OS: OS X 10.13.6
* VS Code version: 1.25.1
* Terraform version: irrelevant 

Edit: add VS Code version & remove terraform version

**Comment by brandoconnor** [comment]
Hey @io41 

I think this is a known bug. I'm not totally sure but I would wager this is more an issue with how the snippets engine works than this particular snippet provider. Can you cite any snippets extensions that don't work this way?

**Comment by io41** [comment]
I just did some testing with various snippet extensions. [Simple Terraform Snippets](https://marketplace.visualstudio.com/items?itemName=loganarnett.tf-snippets) doesn't suffer from the same issue.

**Comment by brandoconnor** [comment]
With recent changes to vscode, this is all of a sudden working for me. Please reopen if that's not the case for you.
